
http://data.fixer.io/api/latest?access_key=6d72d36d698dfa7a26c809e8d5a708e6&format=1&base=EUR

http://data.fixer.io/api/latest?access_key=6d72d36d698dfa7a26c809e8d5a708e6&format=1


http://data.fixer.io/api/symbols?access_key=6d72d36d698dfa7a26c809e8d5a708e6&format=1